#!/usr/bin/env sh

# SIGTERM-handler
term_handler() {
  exit 0;
}

# on callback, kill the last background process, which is `tail -f /dev/null`
# and execute the specified handler
trap 'kill ${!}; term_handler' SIGTERM

# wait indefinetely
while true
do
  tail -f /dev/null & wait ${!}
done
